# Generated by Django 2.1.1 on 2018-10-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20181018_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='qtn',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
