# Generated by Django 2.1.1 on 2018-11-20 17:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0004_submissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('user_id', 'qtn_id')},
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('survey_id', 'qtn')},
        ),
    ]
