# Generated by Django 2.1.1 on 2018-11-23 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20181120_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='privatedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='surveys',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveys',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='qtn',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='privatedetails',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveys'),
        ),
    ]
